name: CI - Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build x64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Setup devcmd
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Build Stremio
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare build artifacts
        run: |
          New-Item -ItemType Directory -Force portable | Out-Null

          Copy-Item target/x86_64-pc-windows-msvc/release/stremio-shell-ng.exe portable
          Copy-Item libmpv-2.dll portable
          Copy-Item server.js portable
          Copy-Item bin/* portable

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: stremio-portable-win64
          path: portable
          if-no-files-found: error
